### ISSUE TITLE
Documentation fix

### ISSUE THREAD

**Issue by GWHAYWOOD** [fmbla/spamassassin#3]
In page http://bl.fmb.la/pages/about/#response-codes

ptr/helo string 	127.0.0.2 	static 	Naming indicates static assigning of addresses
ptr/helo string 	127.0.0.3 	dynamic 	Naming indicates static assigning of addresses

s/(dynamic.*) static/$1 dynamic/;

**Comment by steadramon** [comment]
sa.fmb.la no longer an official zone. Documentation on re-release
